swagger: "2.0"

info:
  description: Official documentation for Invillia Order API
  version: 1.0.0
  title: Invillia Order Service
  termsOfService: http://localhost:8002/invillia/terms
  contact:
    name: Administrator
    url: http://localhost:8002/invillia/support
    email: administrator@invillia.com
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: localhost:8002
basePath: /invillia

tags:
- name: orders
  description: Everything about orders
  externalDocs:
    description: Find out more
    url: http://invillia.com/orders
- name: itemOrders
  description: Everything about item orders
  externalDocs:
    description: Find out more
    url: http://invillia.com/items
- name: addresses
  description: Everything about addresses
  externalDocs:
    description: Find out more
    url: http://invillia.com/address
    
schemes:
- http

paths:
  /store/{storeId}/order:
    get:
      tags:
      - orders
      summary: get all orders
      description: get all orders from database
      operationId: getOrders
      parameters: 
        - name: storeId
          in: path
          type: integer
          format: int64
          required: true
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Order'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorMessage'
            
    post:
      tags:
      - orders
      summary: Create a new order
      description: Create a new instance of an order object
      operationId: addOrder
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: storeId
        in: path 
        type: integer
        format: int64
        required: true
      - in: body
        name: order_
        required: true
        schema:
          $ref: '#/definitions/Order'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Order'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/ErrorMessage'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/ErrorMessage'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorMessage'    
            
  /order/{id}:     
    get:
      tags:
      - orders
      summary: Get an order
      description: Get an order by id
      operationId: getOrder
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Order'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/ErrorMessage'
        500:
          description: Internal server error
          
    put:
      tags:
      - orders
      summary: Update an order
      description: update an order since it is not in CLOSED status
      operationId: updateOrder
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/Order'
      responses:
        204:
          description: No content
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/ErrorMessage'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/ErrorMessage'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorMessage'  
            
    delete:
      tags:
      - orders
      summary: Remove an order
      description: Remove an order since it is not in CLOSED status
      operationId: deleteOrder
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      responses:
        204:
          description: No content
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/ErrorMessage'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/ErrorMessage'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorMessage'   
            
  /order/{orderId}/item:
    get:
      tags:
      - itemOrders
      summary: Get all items of an order
      description: Get all items of an order by id
      operationId: getOrderItems
      produces:
      - application/json
      parameters:
      - name: orderId
        in: path
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/OrderItem'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/ErrorMessage'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorMessage'
            
    post:
      tags:
      - itemOrders
      summary: Add an order item in a order object
      description: Add an order item in a order object
      operationId: addOrderItem
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: orderId
        in: path
        required: true
        type: integer
        format: int64
      - in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/OrderItem'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/OrderItem'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/ErrorMessage'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorMessage'  
    
  /order/{orderId}/item/{id}:
    put:
      tags: 
        - itemOrders
      summary: Update on item
      description:  Update on item
      operationId: updateOrderItem
      produces: 
        - application/json
      consumes:   
        - application/json
      parameters:
        - name: orderId
          in: path
          required: true
          type: integer
          format: int64
        - name: id
          in: path
          required: true
          type: integer
          format: int64 
        - name: item
          in: body
          required: true
          schema:
            $ref: '#/definitions/OrderItem'
      responses:
        204:
          description: No content
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/ErrorMessage'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/ErrorMessage'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorMessage'
    
    delete:
      tags: 
        - itemOrders
      summary: Remove an item from an order
      description: Remove an item from an order
      operationId: deleteOrderItem 
      parameters:
      - name: orderId
        in: path
        required: true
        type: integer
        format: int64
      - name: id
        in: path
        required: true
        type: integer
        format: int64  
      responses:
        204:
          description: No content
        404: 
          description: Not found
          schema:
            $ref: '#/definitions/ErrorMessage'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorMessage'
    
            
definitions:
  Order:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      confirmationDate:
        type: string
        example: 2019-02-21
      status:
        type: string
        example: CLOSED
      items:
        type: array
        items:
          $ref: '#/definitions/OrderItem'
      addresses:
        type: array
        items:
          $ref: '#/definitions/Address'
          
  OrderItem:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      description:
        type: string
        example: Order description
      unitPrice:
        type: number
        format: float
        example: 137.9
      quantity:
        type: integer
        format: int16
        example: 10
      order:
        $ref: '#/definitions/Order'  
        
  Address:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      city:
        type: string
        example: "Los Angeles"
      state:
        type: string
        example: "California"
      postalCode:
        type: string
        example: "899556"
      order:
        $ref: '#/definitions/Order'  
        
  ErrorMessage:
    type: object
    properties:
      description:
        type: string
        example: An error has ocurred
      documentation:
        type: string
        example: http://invilia.com/store/service/errors/list/#field_required      